DROP TABLE IF EXISTS env_monitor_data;

CREATE TABLE env_monitor_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(64) NOT NULL,
    family_id INT NOT NULL,
    room_id INT NULL,
    mq2_adc INT NULL,
    sht30_temp_raw VARCHAR(50) NULL,
    sht30_humi_raw VARCHAR(50) NULL,
    bh1750_raw INT NULL,
    accel_x INT NULL,
    accel_y INT NULL,
    accel_z INT NULL,
    gyro_x INT NULL,
    gyro_y INT NULL,
    gyro_z INT NULL,
    mpu_temp_raw VARCHAR(50) NULL,
    pir_gpio INT NULL,
    body_state VARCHAR(20) NULL,
    key_adc INT NULL,
    uart_rx_len INT NULL,
    uart_rx_hex VARCHAR(20) NULL,
    wifi_conn_state INT NULL,
    wifi_state VARCHAR(20) NULL,
    wifi_rssi INT NULL,
    wifi_ip INT NULL,
    wifi_band INT NULL,
    wifi_frequency INT NULL,
    raw_data JSON NULL,
    timestamp DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_device_id (device_id),
    INDEX idx_family_id (family_id),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
